version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
    depends_on: 
      - api
      - client
  postgres:
    image: 'postgres:latest' # image found through dockerhub
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    depends_on: 
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server # the purpose of context is to indicate where to find the Dockerfile, look in current directory for server directory
    volumes:
      - /app/node_modules # do not try to update/overwrite this file in the container working directory (/app)
      - ./server:/app # copy contents of server directory into container working directory (/app), this prevents the need to update the image on each file change
    environment:
      - REDIS_HOST=redis   #single dash specifies an array entry
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379

